trigger:
- none

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/RoundTheCode.AzureTestProject.sln'
  project: '**/RoundTheCode.AzureTestProject.csproj'

stages:

- stage: Build
  displayName: 'Build'
  jobs:    
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'NuGet tool installer'

    - task: NuGetCommand@2
      displayName: 'NuGet restore packages'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(project)'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: false
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'AzureTestProject'
        publishLocation: 'Container'

- stage: DeployWebsite
  displayName: 'Deploy website'        
  jobs:    
  - deployment: DeployWebsite
    displayName: 'Deploy website'
    environment: 'Windows 11 server.WebserverIIS'
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:           
          steps:
          - checkout: none
          
          - download: 'current'
            displayName: 'Download build artifacts'
            artifact: 'AzureTestProject'
